- name: install extra packages for enterprise linux
  ansible.builtin.yum:
    name: epel-release
    state: installed
- name: Temporarily set SELinux to permissive mode
  ansible.builtin.command: setenforce 0