- name: Install Node.js repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS # change
  ansible.builtin.yum:
    name: nodejs
    state: installed 