- name: reload daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: enable/restart {{component}} service
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: true